// components/Footer.vue
<template>
  <div class="border-t border-gray-400 border-dotted text-center py-5 flex justify-center gap-3">
    <a href="https://github.com/maxigimenez" title="Check my Github profile" target="_blank">
      <Icon name="uil:github" size="1.5em" />
    </a>
    <a href="https://gitlab.com/maxigimenez" title="Check my GitLab profile" target="_blank">
      <Icon name="uil:gitlab" size="1.5em" />
    </a>
    <a href="https://www.linkedin.com/in/maxigimenez/" title="Check my LinkedIn profile" target="_blank">
      <Icon name="uil:linkedin" size="1.5em" />
    </a>
    <a href="https://twitter.com/gmaxi_" title="Reach me out on twitter" target="_blank">
      <Icon name="uil:x" size="1.5em" />
    </a>
    <a href="https://instagram.com/gmaxi_" title="Follow me on Instagram" target="_blank">
      <Icon name="uil:instagram" size="1.5em" />
    </a>
    <a href="mailto:gimenez.maxi@gmail.com" title="Send me an email!" target="_blank">
      <Icon name="uil:inbox" size="1.5em" />
    </a>
  </div>
</template>

// components/footer.tsx
const Footer = () => (
  <div className="border-t border-gray-400 border-dotted text-center py-5">
    <a href="https://twitter.com/gmaxi_" title="Reach me out on twitter" target="_blank">
      <i className="fa fa-twitter text-xl px-3"></i>
    </a>
    <a href="https://instagram.com/gmaxi_" title="Follow me on Instagram" target="_blank">
      <i className="fa fa-instagram text-xl px-3"></i>
    </a>
    <a href="mailto:gimenez.maxi@gmail.com" title="Send me an email!" target="_blank">
      <i className="fa fa-at text-xl px-3"></i>
    </a>
    <a href="https://github.com/maxigimenez" title="Check my Github profile" target="_blank">
      <i className="fa fa-github text-xl px-3"></i>
    </a>
    <a href="https://gitlab.com/maxigimenez" title="Check my GitLab profile" target="_blank">
      <i className="fa fa-gitlab text-xl px-3"></i>
    </a>
    <a href="https://angel.co/maxigimenez" title="Check my Angel List profile" target="_blank">
      <i className="fa fa-angellist text-xl px-3"></i>
    </a>
    <a href="https://www.producthunt.com/@gmaxi_" title="Check my Product Hunt profile" target="_blank">
      <i className="fa fa-product-hunt text-xl px-3"></i>
    </a>
    <a href="https://www.linkedin.com/in/maxigimenez/" title="Check my LinkedIn profile" target="_blank">
      <i className="fa fa-linkedin text-xl px-3"></i>
    </a>
  </div>
);

export default Footer;
