// components/Footer.tsx
export function Footer() {
  return (
    <footer className="border-t border-border">
      <div className="container py-8 flex flex-col sm:flex-row items-center justify-between gap-4">
        <p className="font-mono text-xs text-muted-foreground text-center sm:text-left">
          © {new Date().getFullYear()} Maxi Gimenez
        </p>
        <div className="flex items-center gap-5">
          <a
            href="https://github.com/maxigimenez"
            target="_blank"
            rel="noopener noreferrer"
            className="font-mono text-xs text-muted-foreground hover:text-foreground transition-colors"
          >
            github
          </a>
          <a
            href="https://linkedin.com/in/maxigimenez"
            target="_blank"
            rel="noopener noreferrer"
            className="font-mono text-xs text-muted-foreground hover:text-foreground transition-colors"
          >
            linkedin
          </a>
          <a
            href="mailto:gimenez.maxi@gmail.com"
            className="font-mono text-xs text-muted-foreground hover:text-foreground transition-colors"
          >
            email
          </a>
        </div>
      </div>
    </footer>
  );
}

// components/Footer.vue
<template>
  <div class="glass-panel soft-border flex flex-wrap items-center justify-between gap-4 px-5 py-4 text-sm text-slate-700">
    <div class="flex items-center gap-2 text-slate-600">
      <span class="h-2 w-2 rounded-full bg-emerald-500"></span>
      <span>Coding</span>
    </div>
    <div class="flex items-center gap-3">
      <a href="https://github.com/maxigimenez" title="Check my Github profile" target="_blank" class="hover:text-slate-900">
        <Icon name="uil:github" size="1.4em" />
      </a>
      <a href="https://www.linkedin.com/in/maxigimenez/" title="Check my LinkedIn profile" target="_blank" class="hover:text-slate-900">
        <Icon name="uil:linkedin" size="1.4em" />
      </a>
      <a href="mailto:gimenez.maxi@gmail.com" title="Send me an email!" target="_blank" class="hover:text-slate-900">
        <Icon name="uil:inbox" size="1.4em" />
      </a>
    </div>
  </div>
</template>
